apiVersion: apps/v1
kind: Deployment
metadata:
  name: json-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: json-server
  template:
    metadata:
      labels:
        app: json-server
    spec:
      containers:
        - name: json-server
          image: naveendra/json-server:v1
          resources:
            requests:
              memory: "256Mi"
              cpu: "0.5"
            limits:
              memory: "512Mi"
              cpu: "1"
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: json-data-volume
              mountPath: /app/data   # Mount path inside the container
      volumes:
        - name: json-data-volume
          persistentVolumeClaim:
            claimName: json-server-pvc

